### PR TITLE
Merge updates into orm

### PR DESCRIPTION
**Pull request by theconstellationiris**
This branch has updates from the synced fork of the upstream project, but we typically point SPM to the `orm` branch; the [coinciding PR for this](https://github.com/oreillymedia/puffin/pull/4343) is currently pointed to the ticket branch, and this will instead allow us to point it to `orm` (after this is merged).

### CODE REVIEW

**Comment by lj-dickey** [comment]
So, how did you merge the newest changes on `main` in the original repo into your PR branch? In the past, what we've done is merge `origin/main` into `orm` (see commit `022ba98` or `70638ab`. ). The last successful commit we had been using was `ce751cc`, which pre-dated us merging in `origin/main` in `70638ab`, because that newer merge broke the web view snapshots.  If that issue is fixed now, then we can definitely move to a newer version of the library.  The way the git history looks right now, though, is not a merge of `main` into `orm`, but rather all of the newer changes in the remote repo showing up in your PR branch, which seems a bit confusing -- it makes it less clear where we've chosen to move to the newer version of the remote library by not having a merge from main.

**Comment by theconstellationiris** [comment]
Okay, so we're keeping `main` up to date with upstream, and just merging in to `orm` when it's time for us to update?

**Comment by lj-dickey** [comment]
Yup... that had been our plan all along, and it fell apart when the "latest" snapshot library couldn't pass our CI.  So, we've been stuck on an older merge point, even though `main` was newer.

**Comment by theconstellationiris** [comment]
Okay, cool — I'll close this, and open up a PR for that. Thanks!

**Pull request closed without merging**
